// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.teligen.fileDetector.generate;

public interface DetectedFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:teligen.DetectedFile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * tika  --&gt; 内容  html&lt;h2&gt; --- &lt;/h&gt;
   * </pre>
   *
   * <code>string detContent = 3;</code>
   */
  java.lang.String getDetContent();
  /**
   * <pre>
   * tika  --&gt; 内容  html&lt;h2&gt; --- &lt;/h&gt;
   * </pre>
   *
   * <code>string detContent = 3;</code>
   */
  com.google.protobuf.ByteString
      getDetContentBytes();

  /**
   * <pre>
   * map  &lt;标签类型， 值&gt;
   * mimeType -- xxx
   * sufix -- xx
   * enc -- yes/no
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <pre>
   * map  &lt;标签类型， 值&gt;
   * mimeType -- xxx
   * sufix -- xx
   * enc -- yes/no
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <pre>
   * map  &lt;标签类型， 值&gt;
   * mimeType -- xxx
   * sufix -- xx
   * enc -- yes/no
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <pre>
   * map  &lt;标签类型， 值&gt;
   * mimeType -- xxx
   * sufix -- xx
   * enc -- yes/no
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * map  &lt;标签类型， 值&gt;
   * mimeType -- xxx
   * sufix -- xx
   * enc -- yes/no
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  java.lang.String getTagsOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, string&gt; details = 5;</code>
   */
  int getDetailsCount();
  /**
   * <code>map&lt;string, string&gt; details = 5;</code>
   */
  boolean containsDetails(
      java.lang.String key);
  /**
   * Use {@link #getDetailsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getDetails();
  /**
   * <code>map&lt;string, string&gt; details = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDetailsMap();
  /**
   * <code>map&lt;string, string&gt; details = 5;</code>
   */

  java.lang.String getDetailsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; details = 5;</code>
   */

  java.lang.String getDetailsOrThrow(
      java.lang.String key);
}
