// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.teligen.fileDetector.generate;

public final class File {
  private File() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teligen_UndetectedFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teligen_UndetectedFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teligen_DetectedFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teligen_DetectedFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teligen_DetectedFile_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teligen_DetectedFile_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teligen_DetectedFile_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teligen_DetectedFile_DetailsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfile.proto\022\007teligen\"=\n\016UndetectedFile\022" +
      "\014\n\004uuid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\017\n\007content\030\003" +
      " \001(\014\"\377\001\n\014DetectedFile\022\014\n\004uuid\030\001 \001(\t\022\014\n\004n" +
      "ame\030\002 \001(\t\022\022\n\ndetContent\030\003 \001(\t\022-\n\004tags\030\004 " +
      "\003(\0132\037.teligen.DetectedFile.TagsEntry\0223\n\007" +
      "details\030\005 \003(\0132\".teligen.DetectedFile.Det" +
      "ailsEntry\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001\032.\n\014DetailsEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012\225\001\n\021FileDetectSer" +
      "vice\022:\n\006detect\022\027.teligen.UndetectedFile\032" +
      "\025.teligen.DetectedFile\"\000\022D\n\014streamDetect" +
      "\022\027.teligen.UndetectedFile\032\025.teligen.Dete" +
      "ctedFile\"\000(\0010\001B%\n!com.teligen.fileDetect" +
      "or.generateP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_teligen_UndetectedFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_teligen_UndetectedFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teligen_UndetectedFile_descriptor,
        new java.lang.String[] { "Uuid", "Name", "Content", });
    internal_static_teligen_DetectedFile_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_teligen_DetectedFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teligen_DetectedFile_descriptor,
        new java.lang.String[] { "Uuid", "Name", "DetContent", "Tags", "Details", });
    internal_static_teligen_DetectedFile_TagsEntry_descriptor =
      internal_static_teligen_DetectedFile_descriptor.getNestedTypes().get(0);
    internal_static_teligen_DetectedFile_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teligen_DetectedFile_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_teligen_DetectedFile_DetailsEntry_descriptor =
      internal_static_teligen_DetectedFile_descriptor.getNestedTypes().get(1);
    internal_static_teligen_DetectedFile_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teligen_DetectedFile_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
